/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MerchandiseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "RETRY_LIMIT"
      | "getDataHash"
      | "getOwner"
      | "getPrice"
      | "getProgressBuyer"
      | "getRetryLimit"
      | "getState"
      | "getTrialCount"
      | "i_price"
      | "isConfirmedBuyer"
      | "purchase"
      | "s_confirmedBuyers"
      | "s_merchandiseState"
      | "s_progressBuyer"
      | "s_trialCount"
      | "verify"
      | "withdraw"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Purchase" | "Verify"): EventFragment;

  encodeFunctionData(
    functionFragment: "RETRY_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDataHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getProgressBuyer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRetryLimit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getState", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTrialCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_price", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isConfirmedBuyer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "purchase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_confirmedBuyers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_merchandiseState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_progressBuyer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_trialCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "verify", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "RETRY_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProgressBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRetryLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTrialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_price", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isConfirmedBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_confirmedBuyers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_merchandiseState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_progressBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_trialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace PurchaseEvent {
  export type InputTuple = [owner: AddressLike, buyer: AddressLike];
  export type OutputTuple = [owner: string, buyer: string];
  export interface OutputObject {
    owner: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifyEvent {
  export type InputTuple = [
    owner: AddressLike,
    buyer: AddressLike,
    result: boolean
  ];
  export type OutputTuple = [owner: string, buyer: string, result: boolean];
  export interface OutputObject {
    owner: string;
    buyer: string;
    result: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Merchandise extends BaseContract {
  connect(runner?: ContractRunner | null): Merchandise;
  waitForDeployment(): Promise<this>;

  interface: MerchandiseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  RETRY_LIMIT: TypedContractMethod<[], [bigint], "view">;

  getDataHash: TypedContractMethod<[], [string], "view">;

  getOwner: TypedContractMethod<[], [string], "view">;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getProgressBuyer: TypedContractMethod<[], [string], "view">;

  getRetryLimit: TypedContractMethod<[], [bigint], "view">;

  getState: TypedContractMethod<[], [bigint], "view">;

  getTrialCount: TypedContractMethod<[], [bigint], "view">;

  i_price: TypedContractMethod<[], [bigint], "view">;

  isConfirmedBuyer: TypedContractMethod<
    [buyer: AddressLike],
    [boolean],
    "view"
  >;

  purchase: TypedContractMethod<[], [void], "payable">;

  s_confirmedBuyers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  s_merchandiseState: TypedContractMethod<[], [bigint], "view">;

  s_progressBuyer: TypedContractMethod<[], [string], "view">;

  s_trialCount: TypedContractMethod<[], [bigint], "view">;

  verify: TypedContractMethod<[dataHash: BytesLike], [void], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "RETRY_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDataHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProgressBuyer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRetryLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrialCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isConfirmedBuyer"
  ): TypedContractMethod<[buyer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "purchase"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "s_confirmedBuyers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "s_merchandiseState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_progressBuyer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "s_trialCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[dataHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Purchase"
  ): TypedContractEvent<
    PurchaseEvent.InputTuple,
    PurchaseEvent.OutputTuple,
    PurchaseEvent.OutputObject
  >;
  getEvent(
    key: "Verify"
  ): TypedContractEvent<
    VerifyEvent.InputTuple,
    VerifyEvent.OutputTuple,
    VerifyEvent.OutputObject
  >;

  filters: {
    "Purchase(address,address)": TypedContractEvent<
      PurchaseEvent.InputTuple,
      PurchaseEvent.OutputTuple,
      PurchaseEvent.OutputObject
    >;
    Purchase: TypedContractEvent<
      PurchaseEvent.InputTuple,
      PurchaseEvent.OutputTuple,
      PurchaseEvent.OutputObject
    >;

    "Verify(address,address,bool)": TypedContractEvent<
      VerifyEvent.InputTuple,
      VerifyEvent.OutputTuple,
      VerifyEvent.OutputObject
    >;
    Verify: TypedContractEvent<
      VerifyEvent.InputTuple,
      VerifyEvent.OutputTuple,
      VerifyEvent.OutputObject
    >;
  };
}
